### PR TITLE
Refatcoring and peformance improvements

### PR DESCRIPTION
**Pull request by bobo-k2**
Moved loaded tokens to Vuex so they are not loaded multiple times and refactored most of olde logic. This is still work in progress, but I am creating this PR so other can take a sneak peak to the viewer

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@impelcrypto are you fixing the hover state and the state when equipped too?
スクリーンショット 2023-03-27 11 37 15

**Comment by Kahonnohak** [comment]
Hi @bobo-k2 I like the Asset page like this!!

@impelcrypto I add some styling fix here on this PR if this is ok. The other one should be merged? 

Asset page:
- Please remove the margin of 12px on the right.
スクリーンショット 2023-03-27 11 21 27

Parent Page
**Main NFT** 
- I think it is okay to have the background and better to have it to show dark coloured parts NFTs, however it looks like as it is a part of the NFT. Could you make the background gradients opacity 0.2 please? (For all tokens)
- Can we have the loading in the centre please
- Attributes : Could we keep the paddings 16px and keep the centre-align please?
スクリーンショット 2023-03-27 11 30 25
スクリーンショット 2023-03-27 12 12 22


- Please replace the logo and footer logo.
Astar_logo_builtby
Astar_nft_logo


**Child NFT**
- Please move the buttons left aligned and change the size of the button to 130ox same as the Share and Refresh. The equip icons look bolder than it should be. (I'll provide the links)

**Comment by Kahonnohak** [comment]
Also please update the colour of the wallet modal. (note to add drop shadow on X side) 
https://www.figma.com/file/qrqYSYUH8hgXMY5FxWRYbt/NFT-viewer?node-id=1294%3A16563&t=DVs3VGxfbRBfDgFZ-1

**Comment by bobo-k2** [comment]
@impelcrypto do you have a time to address comments related to styling?

**Comment by impelcrypto** [comment]
@bobo-k2  Sure, let me work on updating styling. I'll create a PR within this week.

**Review by impelcrypto — APPROVED** [review]

**Comment by bobo-k2** [comment]
> @bobo-k2 Sure, let me work on updating styling. I'll create a PR within this week.

Thanks Roy. I will merge this PR than and let you work on above comments in the new one.

**Pull request merged**
