### PR TITLE
Add child NFT

### PR DESCRIPTION
**Pull request by bobo-k2**
This PR enables adding a token as a child of another token. To try the feature mint StrBods and StrEyes tokens here:
https://ink-nft-246a8--pr22-feat-add-child-xm7rzrb1.web.app/shibuya-testnet/strbods/mint
https://ink-nft-246a8--pr22-feat-add-child-xm7rzrb1.web.app/shibuya-testnet/streyes/mint

Go to assets page, click star and click Add button from Inventory. The dialog to add child pops
image

Ignore code in `modules` folder since it is autogenerated
Close #14

### CODE REVIEW

**Comment by Kahonnohak** [comment]
My requests
1)  After mint, can you direct users to the asset page (or shall we add "go to Asset Page")
2) Where do you get those collection icons? Who uploads them?
3) Please replace the logo (ink!redible NFT) (desktop 20px height and mobile 18px height)
4) Please change the footer with Built by Astar (so, the social icons on the left and Built by Astar will stay on the right bottom)

Ink!redibleNFT

landing-m
landing

Figma:
https://www.figma.com/file/qrqYSYUH8hgXMY5FxWRYbt/NFT-viewer?type=design&node-id=254%3A25728&t=KmPo3thZRirUzuQm-1

**Review by gluneau — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
Maybe unify the unit to SBY as not many people understand what is nSBY and mSBY? 
image

**Comment by impelcrypto** [comment]
It seems that the mint transactions have succeeded but I can't see child NFTs in the modal.

https://shibuya.subscan.io/extrinsic/3962982-4

https://shibuya.subscan.io/extrinsic/3962978-3

image

**Comment by Kahonnohak** [comment]
> Maybe unify the unit to SBY as not many people understand what is nSBY and mSBY? image

The main release happens only on Astar so lets leave it.

**Comment by Kahonnohak** [comment]
@impelcrypto No we don't. But as far as I know the storage deposit will be 3ASTR and the gas fee is around 0.12ASTR~ so I believed this was because SBY costs a lot cheaper than Astar. hehe but I'm sure Bobo can take a look!

**Comment by bobo-k2** [comment]
> 5\. inkredible-nft.astar.network

Yes, fees on Astar are much higher and display should be ok. Another drawback of removing m or n prefix is that we will have to many zeros like 0.0000000000xx

**Comment by Kahonnohak** [comment]
Thank you @bobo-k2 . Got it, it's fine we don't have to be fussy about small things now. 

The footer Built by Astar you probably found from the previous PR has a typo. I got a new SVG. Please replace it.
BuiltbyAstar

Also sorry but could you take a look at Meta descriptions please? I thought I would make a commit but I was afraid that i might even make a mess.

Astar NFT -> ink!redible NFT

Screenshot 2023-06-08 at 19 48 26

**Comment by bobo-k2** [comment]
> ink!redible NFT

@Kahonnohak, no problem, fixed in  the last commit

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
> https://github.com/AstarNetwork/ink-redible-nft/pull/22#issuecomment-1582325490 It seems that the mint transactions have succeeded but I can't see child NFTs in the modal.

It seems that the issue has been resolved.

image

**Comment by Kahonnohak** [comment]
@bobo-k2 
I got two same tokens in the asset page, I assume one is the token, and the other one appeared after equipping? 

Screenshot 2023-06-09 at 12 48 46

**Comment by Kahonnohak** [comment]
> > ink!redible NFT
> 
> @Kahonnohak, no problem, fixed in the last commit

Thank you! all checked!

**Review by sirius651 — APPROVED** [review]

**Comment by bobo-k2** [comment]
> @bobo-k2 I got two same tokens in the asset page, I assume one is the token, and the other one appeared after equipping?

Already fixed but in another branch :)

**Pull request merged**
