### PR TITLE
Accept (bond) child

### PR DESCRIPTION
**Pull request by bobo-k2**
The PR is about accepting child tokens. Unaccepted tokens are displayed in parent token inventory in grayscale
image

After clicking the child token modal is poped with option to Bond the child
image

Moved some code from #14 to this PR.

### CODE REVIEW

**Comment by impelcrypto** [comment]
Weird, I can't see my NFTs here
image

**Comment by sirius651** [comment]
> Weird, I can't see my NFTs on Assets page

maybe because base contract has been changed?

**Comment by Kahonnohak** [comment]
- Could you make colour changes please (grey to navy)

.body--dark .modalbg[data-v-393868e4] {
    -webkit-backdrop-filter: blur(50px);
    backdrop-filter: blur(50px);
    **background: #081029b3;**

.body--dark .modal-content[data-v-393868e4] {
    **background: #081029b3;**
    
- Could you also add the row--description please (see other models in screenshot below), also I throw a question about the wording on Slack so it depends on what we decide please change the wording accordingly. 

    
"row--description" 
This NFT has not yet been added to the parent NFT's inventory. By "Accepting" the NFT to the parent, it will be added to the parent inventory and you will be able to "equip" the child. Please note that once the child NFT is accepted, it cannot be removed from the inventory.

スクリーンショット 2023-04-14 9 23 26

**Comment by bobo-k2** [comment]
@Kahonnohak I have two comments
- regarding accept child dialog text. Have in mind that child can be removed, but this is not supported in UI yet, so maybe to reformulate sentence a bit. 
- to which page to add 'Back to assets'? Parent page?

**Comment by Kahonnohak** [comment]
> @Kahonnohak I have two comments
> 
> * regarding accept child dialog text. Have in mind that child can be removed, but this is not supported in UI yet, so maybe to reformulate sentence a bit.
> * to which page to add 'Back to assets'? Parent page?

Ah yes thanks then something like :

`This NFT has not yet been added to the parent NFT's inventory. By "Accepting" the NFT to the parent, it will be added to the parent inventory and you will be able to "equip" the child. Please note that it is still under development that the UI is not able to remove the NFT from the inventory at this moment. `

Or please make changes!

I think Back to Assets should be all NFT (parent and child) pages.

**Comment by bobo-k2** [comment]
@Kahonnohak I believe I addressed all your comments. Please recheck.

**Comment by Kahonnohak** [comment]
Hi I'll just mention again here!

- All the fixes you made are working good now!
- New things,  I got my first NFT back in my account and the children that have not been accepted disappeared from the Asset page.
Screenshot 2023-04-18 at 11 08 43
Screenshot 2023-04-18 at 11 08 59




Could you also add meta info please

Title: Astar NFT
Description: Astar NFT showcases the first RMRK NFT smart contracts using ink!.
og;img: attached

AstarNFT-ogp

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Review by impelcrypto — APPROVED** [review]

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
