### PR TITLE
Gas limit fix

### PR DESCRIPTION
**Pull request by bobo-k2**
Fix for OutOfGas issue. I wasn't able to test this further because I don't have any token minted on Shibuya test contract

### CODE REVIEW

**Comment by impelcrypto** [comment]
@bobo-k2 
Now I got this error🤔
image

**Comment by bobo-k2** [comment]
> @bobo-k2 Now I got this error🤔

Are you getting this for Equip call?
image

**Comment by impelcrypto** [comment]
No, I tried sending `Unequip` transaction only.

**Comment by impelcrypto** [comment]
I got this after calling `Equip` transaction (there is no error in console)

image

**Comment by impelcrypto** [comment]
I got this after calling `Equip` transaction (there is no error in console)

image

**Comment by bobo-k2** [comment]
> I got this after calling `Equip` transaction (there is no error in console)

Try to redeploy contract with the script. I had the same problem until I redeployed. Most likely there is an difference between contract deployed and one we are using in UI.

Equip and Unequip should work fine after the last commit.

**Comment by impelcrypto** [comment]
@bobo-k2 
I see, how about changing contracts and related files to your latest files then test it again with your wallet? If all good, you can commit it with changes.

https://github.com/AstarNetwork/ink-redible-nft/blob/feat/fetch-from-chain/src/hooks/useNft.ts#L25

**Comment by bobo-k2** [comment]
> @bobo-k2 I see, how about changing contracts and related files to your latest files then test it again with your wallet? If all good, you can commit it with changes.
> 
> https://github.com/AstarNetwork/ink-redible-nft/blob/feat/fetch-from-chain/src/hooks/useNft.ts#L25

I am not feeling comfortable sharing an account private key, even for test account. I hope soon we will have a better collection deployed on Shibuya so everyone can try.

**Comment by impelcrypto** [comment]
Oh, you don't have to share your private key. I mean, you can change the contract addresses and test it with your wallet (by you :D I don't need to test it). Then we can merge this PR if everything works fine. Or we can test it later like you said.

**Comment by bobo-k2** [comment]
> Oh, you don't have to share your private key. I mean, you can change the contract addresses and test it with your wallet (by you :D I don't need to test it). Then we can merge this PR if everything works fine. Or we can test it later like you said.

Sorry, I misunderstood you. I will test today

**Comment by impelcrypto** [comment]
@bobo-k2 
I just tried `unequip` and it worked!

**Comment by impelcrypto** [comment]
worked `equip` as well!
image

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
